myfirst/apps/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('articles/', views.index, name='index'),
    path('articles/<int:article_id>/', views.detail, name='detail'),
    path('articles/<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment'),
    path('articles/create_article/', views.create_article, name='create_article'),
    path('calculator/', views.calculator, name='calculator'),
    path('vitalik/', views.vitalik, name='vitalik'),
    path('registration/', views.register, name='register'),
    path('registration/create_user/', views.create_user, name='create_user'),
    path('vitalik/change_image/', views.change_image, name='change_image'),
   	path('send_message/', views.send_message, name='send_message'),
    path('chat/', views.chat, name='chat'),
    path('get_messages/', views.get_messages, name='get_messages'),
]

myfirst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

#Add Django site authentication urls (for login, logout, password management)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('django.contrib.auth.urls')),
    path('', include('articles.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myfirst/apps/articles/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор статьи')
    article_title = models.CharField('название статьи', max_length=200)
    article_text = models.TextField('текст статьи')
    pub_date = models.DateTimeField('дата публикации')

    def __str__(self):
        return self.article_title

    def was_published_recently(self):
        return self.pub_date >= (timezone.now() - datetime.timedelta(days=7))

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('имя автора', max_length=50)
    comment_text = models.CharField('текст комментария', max_length=200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Images(models.Model):
    image_name = models.CharField('Название изображения', max_length=50)
    image = models.ImageField()
    file = models.FileField()

    def __str__(self):
        return self.image_name

class Message(models.Model):
    naming_message = 'Message'
    username = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор сообщения')
    text = models.TextField('Текст сообщения')
    timestamp = models.TimeField('Время отправки сообщения')

    def __str__(self):
        return self.naming_message

    class Meta:
        verbose_name = 'Message'
        verbose_name_plural = 'Messages'

myfirst/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from .models import Article, Comment, Images, Message
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
import webbrowser
import time
import requests
from bs4 import BeautifulSoup as BS

def index(request):
    latest_article_list = Article.objects.order_by('-pub_date')
    return render(request, 'articles/list.html', {'latest_article_list': latest_article_list})


def detail(request, article_id):
    if request.user.is_authenticated:
        try:
            a = Article.objects.get(id=article_id)
        except:
            raise Http404("Статья не найдена")

        latest_comments_list = a.comment_set.order_by('-id')[:10]

        return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list, })
    else:
        return HttpResponseRedirect("/user/login/")


def leave_comment(request, article_id):
    if request.user.is_authenticated:
        try:
            a = Article.objects.get(id=article_id)
        except:
            raise Http404("Статья не найдена")

        a.comment_set.create(author_name=request.POST['author_name'],
                             comment_text=request.POST['comment_text'])

        return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))
    else:
        return HttpResponseRedirect("/user/login/")


def create_article(request):
    if request.user.is_authenticated:
        a = Article(
            author=request.user,
            article_title=request.POST['article_title'],
            article_text=request.POST['article_text'],
            pub_date=timezone.now())
        a.save()
        return HttpResponseRedirect('/articles/')

    else:
        return HttpResponseRedirect("/user/login/")


def calculator(request):
    return render(request, 'articles/calculator.html')


def vitalik(request):
    all_images = Images.objects.order_by()[:1]
    return render(request, 'articles/lefort_and_not_only.html', {'all_images': all_images})


def register(request):
    return render(request, 'articles/register.html')


def create_user(request):
    user = User.objects.create_user(request.POST['username'], '', request.POST['password'])
    user.save()
    return HttpResponseRedirect("/user/login/")


def change_image(request):
    image = Images.objects.get(id=6)
    try:
        image.image_name = request.POST['change_image_name']
        image.image = request.FILES['photo']
        image.file = request.FILES['audio']
        image.save()
    except Exception:
        return HttpResponseRedirect("/vitalik/")
    return HttpResponseRedirect("/vitalik/")


def send_message(request):
    message = Message(
    username=request.user,
    text=request.POST['text_message'],
    timestamp= timezone.now())
    message.save()
    return HttpResponseRedirect('/chat/')


def chat(request):
    messages = Message.objects.all()
    return render(request, 'messenger/index.html', {'messages': messages})

def get_messages(request):
    #all_usernames = []
    #all_texts = []
    #for i in Message.objects.all():
    #    all_usernames.append(i.username)
    #    all_usernames.append(' ')
    #    all_texts.append(i.text)
    #    all_texts.append(' ')
    #return HttpResponse(all_usernames, all_texts)
    return HttpResponse("1")
    #r = requests.get('http://127.0.0.1:8000/chat')
    #html = BS(r.content, 'html.parser')
    #all_messages = []
    #for el in html.select('.something_class'):
    #    title = el.select('.something_class > p')
    #    all_messages.append(title[0].text)
    #return HttpResponse(all_messages)

myfirst/templates/articles/calculator.html
{% extends 'base.html' %}
{% block title %}Calculator{% endblock %}
{% block content %}

<div id="calc-wrap">
    <div id="calc">
        <textarea id=inputVal>0</textarea>
    </div>
</div>

<script>
// код начнёт выполняться после загрузки страницы
// когда окно загрузится, сработает метод window.onLoad
window.addEventListener('load', function OnWindowLoaded() {
    // набор кнопок
    var signs = [
        '1', '2', '3', '+',
        '4', '5', '6', '-',
        '7', '8', '9', '/',
        '0', '=', '.', 'c', '*'
    ];
 
    // форма калькулятора
    var calc = document.getElementById('calc');
 
    // текстовое поле с математическим выражением
    var textArea = document.getElementById('inputVal');
 
    // Добавление кнопок к форме калькулятора
    signs.forEach(function (sign) {
        var signElement = document.createElement('div');
        signElement.className = 'btn';
        signElement.innerHTML = sign;
        calc.appendChild(signElement);
    });
 
    // проходит по всем кнопкам калькулятора
    // добавляет обработчик на клик
    document.querySelectorAll('#calc-wrap .btn').forEach(function (button) {
        // Добавляем действие, выполняемое при клике на любую кнопку
        button.addEventListener('click', onButtonClick);
    });
 
    // функция клика по кнопке калькулятора
    function onButtonClick(e) {
        // e - MouseEvent (содержит информацию о клике)
        if (e.target.innerHTML === 'c') {
            // Если нажата кнопка "с", то стирает все из текстового поля
            textArea.innerHTML = '0';
        } else if (e.target.innerHTML === '=') {
            // Если нажата кнопка "=", то, приведя выражение
            // в текстовом поле к javascript, вычислить значение
            textArea.innerHTML = eval(textArea.innerHTML);
        } else if (textArea.innerHTML === '0') {
            // Если textarea содержит только "0", то
            // стереть "0" и записать
            // значения кнопки в текстовое поле
            textArea.innerHTML = e.target.innerHTML;
        } else {
            // Добавление значения кнопки в текстовое поле
            textArea.innerHTML += e.target.innerHTML;
        }
    }
});

</script>

<style>
    .btn {
        width: 60px;
        height: 60px;
        background: #7CFC00;
        display: inline-block;
        text-align: center;
        line-height: 60px;
        user-select: none;

    }
 
    .btn:hover {
        background: #f70;
        color: #fff;
    }
 
    #calc-wrap {
        padding: 10px;
        width: 100%;
        text-align: center;
        background: #eee;
    }
 
    #calc {
        width: 240px;
        display: inline-block;
    }
 
    #inputVal {
        width: 100%;
        border: 0;
        font-size: 16px;
        resize: vertical;
    }

</style>

{% if request.user.is_authenticated != True %}
<small class="text-muted">Вы не авторизированы!</small>
{% endif %}

{% endblock %}

myfirst/templates/articles/detail.html
{% extends  'base.html' %}

{% block title %}{{ article.article_title }}{% endblock %}

{% block content %}


<div class="container">
    <div class="alert alert-success" role="alert"><h1>{{ article.article_title }}</h1></div>
    <div class="alert alert-info" role="alert"><p>{{ article.article_text }}</p></div>
    <div class="alert alert-info" role="alert">Автор статьи: {{ article.author }}</div>
    Дата публикации: <em>{{ article.pub_date }}</em>
    <hr>
    {% if latest_comments_list %}
    {% for c in latest_comments_list %}
    <p>
    <div class="alert alert-danger" role="alert">
        <strong>Имя автора: {{c.author_name}}</strong>
    </div>
    <div class="alert alert-secondary" role="alert">
        <p>Текст комментария: {{ c.comment_text }}</p>
    </div>
    </p>
    {% endfor %}
    {% else %}
    Комментарии не найдены! Станьте первым :3
    {% endif %}
    <hr>

    <form action="{% url 'articles:leave_comment' article.id %}" method="POST">
        {% csrf_token %}
        <input type="text" required placeholder="Ваше имя" name="author_name"><br>
        <textarea name="comment_text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea><br>
        <button type="submit" class="btn btn-primary">Оставить комменатрий</button>
    </form>
</div>
{% endblock %}

myfirst/templates/articles/lefort_and_not_only.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <title></title>
</head>
<body class="body_class">
{% block content %}


<div class="parent">

    {% for i in all_images %}
    <script type="text/javascript">
      window.onload = function() {
      let button = document.getElementById("{{ i.image_name }}");
      let audio = new Audio();
      let body = document.getElementsByTagName('body')[0];
      document.querySelector('.myclass').addEventListener('click', function(e){
      if (button){
        body.style.backgroundImage = "url('{{ i.image.url }}')";
        audio.src = '{{ i.file.url }}';
        audio.autoplay = true;
        return false;
      };
    });
    };


    </script>
    <button class="myclass" id="{{ i.image_name }}">{{i.image_name}}</button>
    {% endfor %}
</div>
<br>
<br>
<br>
<div class="form">
    <form action="{% url 'articles:change_image' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="change_image_name" placeholder="Название"><br>
        <input type="file" name="photo" placeholder="Картинка"><br>
        <input type="file" name="audio" placeholder="Аудио"><br>
        <button type="submit" class="btn btn-primary">Change</button>

    </form>
</div>
{% endblock %}
</body>
</html>

myfirst/templates/articles/list.html
{% extends  'base.html' %}

{% block title %}Статьи{% endblock %}

{% block content %}



{% if user.is_authenticated != False %}
    <div class="container">
        {% if latest_article_list %}
    
        {% for a in latest_article_list %}
        <div class="alert alert-primary" role="alert">
            Название статьи: <a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
        </div>
        {% endfor %}
    
        {% else %}
        Статьи не найдены :(
        {% endif %}
    
        <br>
        <form action="{% url 'articles:create_article' %}" method="POST">
            {% csrf_token %}
            <input type="text" required placeholder="Название статьи" name="article_title"><br>
            <textarea name="article_text" required="" placeholder="Текст статьи" cols="30" rows="10"></textarea><br>
            <button type="submit" class="btn btn-primary">Создать статью</button>
        </form>
    </div>
{% else %}
<small class="text-muted">Вы не авторизированы!</small>
{% endif %}



{% endblock %}

myfirst/templates/articles/register.html
{% extends 'base.html' %}
{% block title %} Registration {% endblock %}
{% block content %}

<form action="{% url 'articles:create_user' %}" method="POST">
    {% csrf_token %}
    <input type="text" required placeholder="Никнейм" name="username"><br>
    <input type="text" required placeholder="Пароль" name="password"><br>
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
</form>


{% endblock %}

myfirst/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	{% load static %}
	<title>{% block title %}Мой сайт{% endblock %}</title>

</head>
<body>
	{% block content %}{% endblock %}

</body>
</html>

myfirst/templates/messenger/index.html
{% extends 'base.html' %}
{% block title %}Chat{% endblock %}
{% block content %}

<style>
.prokrutka {
height: 500px; /* высота нашего блока */
width: 500px; /* ширина нашего блока */
background: #fff; /* цвет фона, белый */
border: 1px solid #C1C1C1; /* размер и цвет границы блока */
overflow-x: scroll; /* прокрутка по горизонтали */
overflow-y: scroll; /* прокрутка по вертикали */
margin: auto;
padding:10px;
word-break:break-all;
}
</style>

<div class="prokrutka" align="left">
	{% for message in messages %}
		<div class="something_class"><p>{{message.username}} {{message.text}} {{message.timestamp}}</p></div>
	{% endfor %}
</div>
<form action="{% url 'articles:send_message' %}" method="POST">
	{% csrf_token %}
	<input type="text" name="text_message"><br>
	<button type="submit" class="btn btn-primary">Send Message</button>

</form>

{% endblock %}